services:
  - type: web
    name: tg-link-bot
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8006752451:AAE83g_wFA-6epU7phVznE6a7uuZGR_JDVQ
      - key: API_ID
        value: 29020960
      - key: API_HASH
        value: d2ddcda6864b48aed924dd0a95aed671
      - key: AUTH_USERS
        value: 590048058
